blank_issues_enabled: true
contact_links:
  - name: â“ Questions
    url: https://github.com/cobbler/cobblerclient/discussions
    about: Ask questions here
  - name: ğŸ’¬ Matrix Chat
    url: https://app.element.io/#/room/#cobbler_community:gitter.im
    about: Chat with the Cobbler community
  - name: ğŸ“¬ Development mailing list
    url: https://groups.google.com/forum/#!forum/cobbler-users
    about: The developer mailing list
